#!/bin/sh
ssh ubuntu@ec2-3-142-255-53.us-east-2.compute.amazonaws.com <<EOF
  cd ~/monsters-shoot
  git pull origin master
  curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
  . ~/.nvm/nvm.sh
  nvm install v14.15.4
  cd client
  npm install -g nodemon pm2
  pm2 restart ecosystem.config.js
  exit
EOF